# Generated by Django 2.1.3 on 2018-11-29 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=16)),
                ('status', models.CharField(default='OFF', max_length=10)),
                ('codigo', models.CharField(default='0', max_length=8)),
                ('cor', models.CharField(default='btn btn-danger', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Gpequipamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=16)),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='micro.Equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
