# Generated by Django 2.1.3 on 2018-11-30 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpequipamentos',
            name='nome',
        ),
    ]
