# Generated by Django 2.1.3 on 2018-11-30 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0002_remove_gpequipamentos_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpequipamentos',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micro.Equipamento'),
        ),
    ]
