# Generated by Django 2.1.3 on 2018-12-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0003_auto_20181129_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpequipamentos',
            old_name='grupo',
            new_name='Equipamentos',
        ),
    ]
