# Generated by Django 2.1.3 on 2018-12-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0004_auto_20181206_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpequipamentos',
            name='Equipamentos',
        ),
        migrations.AddField(
            model_name='gpequipamentos',
            name='Equipamentos',
            field=models.ManyToManyField(to='micro.Equipamento'),
        ),
    ]
